### ISSUE TITLE
Trend over Time

### ISSUE THREAD

**Issue by theShmoo** [VALIDproject/mtdb2#32]
Mein Eindruck (mit Hilfe von MTDB2) ist aber das die Quartale hier zu
detailiert sind, weil es bei vielen RT-M Beziehungen nur 1 Peak pro Jahr
(zB immer Q1) oder Peaks jedes zweite Quartal gibt. Deshalb würde ich
den Trend als Vergleich zwischen 2 Jahren abbilden. D.h. bei den
momentanen Daten 2013Q3-2014Q2 versus 2014Q3-2015Q2.

Absolute Veränderung versus Relativ: Ich halte einen relativen Wert mit
dem alten Wert als 100% für am sinnvollsten.

Bsp. Wien->Kurier
2013Q3-2014Q2  1.507.773,46 €
2014Q3-2015Q2  2.030.712,34 €
+35%

In den Tabellen der Rechtsträger und Medien können diese Prozentzahlen
dargestellt (auf ganze Prozent gerundet) und zur Sortierung verwendet
werden.
Grafisch vlt. als Pfeil: 5 Pfeil Icons  hinauf > 100%, schräg hinauf >
20%, gerade nach rechts, schräg hinunter, hinunter
(Aber vlt. fällt dir oder uns da noch was besseres ein.)
Ggf. dafür die Ränder schmäller machen (bei unseren 16:9 Bildschirmen am
PC bleibt da einiges an Platz leer)

Oben bei den Balkendiagrammen könnte Trend analog zu den Ausgaben
funktionieren. Also Trend auf x-Achse. Anzahl der Relationen auf der
y-Achse.

**Comment by theShmoo** [comment]
Meine Anmerkungen dazu:
- Die Pfeile finde ich keine gute Darstellung. Da Winkel schwerer zu interpretieren sind wie Balken. Ich würde vorschlagen Balken wie bei den Relationen nur sie in der Mitte beginnen zu lassen und negativ nach links und positiv nach rechts darstellen
- Was passiert wenn nur ein Quartal gefiltert wird?
- Veränderung hätte ich so berechnet: (neues - altes)/totales
- Willst du wirklich ein zusätzliches Diagramm / Filter in der ersten Reihe? Denkst du nicht dass das schon zu viel wird?

**Comment by theShmoo** [comment]
Was noch fehlt: 
- [ ] Zusätzliches Diagramm in der ersten Reihe. (siehe oben)
- [ ] Was soll passieren wenn nach Quartalen gefiltert wird?
- [ ] Visualisierung in der Table evaluieren

**Comment by alex-rind** [comment]
Berechnung  `(neues - altes)/totales` 

-> ok, so bleiben die Werte wenigstens zw. -100% und +100%

**Comment by alex-rind** [comment]
nach Quartalen gefiltert
- bei nur 1 Quartal -> keine Berechnung durchführen und in der Spalte ein "!" icon und onHover ein Tooltip dass mehr Quartale ausgewählt sein müssen
- bei gerader Anzahl von Quartalen -> Differenz zwischen der neueren und der älteren Hälfte (auch wenn Lücken dazwischen)
- bei ungerader Anzahl -- Schwierig ob das Mittlere jetzt einfach ignoriert werden kann? -> Vorschlag keine Berechnung so wie nur 1 Quartal

**Comment by alex-rind** [comment]
Zusätzliches Diagramm in der ersten Reihe 

-> Ja ich denke das ist (gerade noch) möglich. 
Eher breitere Gruppen vlt. 5% oder 10% probieren

**Comment by alex-rind** [comment]
Visualisierung in Table
- ich fürchte bei dem horizontalen Balken wird man auch nicht viel erkennen, v.a. ob die Breite ins Negative oder Positive geht
- wir präferieren nach wie vor die Pfeile, aber nicht so dass der Winkel genau den Wert kodiert sondern, sondern nur 3 oder 5 Ausprägungen mit Schwellwerten zB -10% bis +10% waagrecht
- zusätzlich Prozent als Zahl

(IMHO wird der größere Mehrwert aus _sortieren_ nach Trend und _filtern_ nach Trend entstehen.)

**Comment by theShmoo** [comment]
> Eher breitere Gruppen vlt. 5% oder 10% probieren
- Was meinst du damit? Die Tics? Meinst du ich sollte ein 5-10% binning machen?
- Welchen Use Case haben überhaupt der Ausgaben Chart und der noch nicht implementierte Trend Chart? 

> nach Quartalen gefiltert

Momentan ist es so dass immer die Mitte aller Quartale angenommen wird und das versteht man als User denke ich recht gut.

> Visualisierung in Table

Hast dus dir schon angeschaut? Ich finde man erkennt es ganz gut... Das größte Problem beim Sortieren ist IMHO das es viele gibt die eben -100% und +100% haben...

**Comment by alex-rind** [comment]
> > Eher breitere Gruppen vlt. 5% oder 10% probieren
> 
> Was meinst du damit? Die Tics? Meinst du ich sollte ein 5-10% binning machen?

Bins (also Balken)

> Welchen Use Case haben überhaupt der Ausgaben Chart und der noch nicht implementierte Trend Chart?

Good question. Die requirements bleiben leider sehr vage, wir suchen "auffälligen" Änderungen. Danach wollen wir filtern.

> > nach Quartalen gefiltert
> 
> Momentan ist es so dass immer die Mitte aller Quartale angenommen wird und das versteht man als User denke ich recht gut.

Ok, lassen wir einmal so. IMHO ist das nicht so intuitive, aber Hauptsache es funktioniert mit allen Quartalen und bleibt auch sonst konsistent.

> > Visualisierung in Table
> 
> Hast dus dir schon angeschaut? Ich finde man erkennt es ganz gut... Das größte Problem beim Sortieren ist IMHO das es viele gibt die eben -100% und +100% haben...

Lassen wir so, funktioniert gut genug (Nachteil dass 2 Farben notwendig)

**Comment by theShmoo** [comment]
Ich habe einen Chart gepushed und ein paar Änderungen gemacht. Vielleicht kannst du dir das anschauen und ein Feedback dazu geben.

**Comment by alex-rind** [comment]
Sieht super aus! Ich zeig's einmal den Kollegen.

Nur: Sortierung Rechtsträger nach Trend geht bei mir nicht.

**Comment by theShmoo** [comment]
Das liegt an dem Layout... Bin grad dabei das zu beheben. Siehe neues
issue... Push ich am Nachmittag!

**Comment by alex-rind** [comment]
moved some diverging ideas to new issues #36 and #37 (tagged as future work)
