### ISSUE TITLE
Sparkline Barcharts

### ISSUE THREAD

**Issue by theShmoo** [VALIDproject/mtdb2#5]
Implement Sparkline Barcharts in tables for development over time.
Something like this:
![](https://cdn.ablebits.com/_img-blog/excel-sparklines/sparklines-types.png)

**Comment by alex-rind** [comment]
+1

**Comment by aiwo77** [comment]
might be useful:
http://dataviztalk.blogspot.co.at/2016/01/how-to-make-tuftes-discrete-sparklines.html?m=1

Am 14.01.2016 um 17:03 schrieb David Pfahler <notifications@github.com<mailto:notifications@github.com>>:

Implement Sparkline Barcharts in tables for development over time.
Something like this:
[https://camo.githubusercontent.com/b4506ea138208069ffe17f4a3e866e97702e36c5/68747470733a2f2f63646e2e61626c65626974732e636f6d2f5f696d672d626c6f672f657863656c2d737061726b6c696e65732f737061726b6c696e65732d74797065732e706e67]https://camo.githubusercontent.com/b4506ea138208069ffe17f4a3e866e97702e36c5/68747470733a2f2f63646e2e61626c65626974732e636f6d2f5f696d672d626c6f672f657863656c2d737061726b6c696e65732f737061726b6c696e65732d74797065732e706e67

##
