### ISSUE TITLE
Persistence from combine and remove operations

### ISSUE THREAD

**Issue by theShmoo** [VALIDproject/mtdb2#6]
It would be nice if the browser would save for a session some remove and combine operations so that after reloading the page this operations are not lost.

**Comment by alex-rind** [comment]
+1
an alternative to client/server would be HTML5 local storage

**Comment by alex-rind** [comment]
this need not be addressed in the current project but should stay open 
(i.e. future work)

**Comment by alex-rind** [comment]
sorry, I didn't notice that commit 76653e6 also added local storage and thus addressed this issue (great work!)
